controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz, suitable for real-time control
    use_sim_time: true  # Required for Gazebo simulation

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

mecanum_drive_controller:
  ros__parameters:
    front_left_wheel_command_joint_name: "front_left_wheel_joint"
    front_right_wheel_command_joint_name: "front_right_wheel_joint"
    rear_left_wheel_command_joint_name: "rear_left_wheel_joint"
    rear_right_wheel_command_joint_name: "rear_right_wheel_joint"

    kinematics:
      circular_radius: 0.1017  # Matches semi-major axis (4 inches)
      semi_major_axis: 0.1017  # 4 inches
      semi_minor_axis: 0.0381  # 1.5 inches
      sum_of_robot_center_projection_on_X_Y_axis: 1.0668  # lx + ly

    base_frame_id: "base_link"
    odom_frame_id: "odom"

    reference_topic: "/mecanum_drive_controller/reference"
    use_stamped_vel: true 

    publish_rate: 50.0
    wheel_separation_x: 0.4318 
    wheel_separation_y: 0.635

    linear.x.max_velocity: 5.0
    linear.y.max_velocity: 5.0
    angular.z.max_velocity: 2.0
    command_timeout: 0.5  # Resets to zero velocity if no command within 0.5s